version: '2'
services:
  opencart:
    build: .
    ports:
     - "80:80"
    volumes:
     - /data/opencart/html:/var/www/html
    depends_on:
     - mysql
  mysql:
    image: mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart

