version: '2'
services:
  opencart:
    build: .
    ports:
     - "80:8081"
    depends_on:
     - mysql
  mysql:
    image: mysql
    ports:
     - "3301:3301"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opencart
      MYSQL_USER: opencart
      MYSQL_PASSWORD: opencart

